ap: Upgrade pip to be compatible with latest cffi
With recently released cffi (1.15.1), the Tox task fails as:
```
x86_64-alt-linux-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -pipe -frecord-gcc-switches -Wall -g -O3 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
  c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
            ^~~~~~~
compilation terminated.
error: command 'x86_64-alt-linux-gcc' failed with exit status 1
```

This version doesn't provide a wheel compatible with P9's pip 19.1.1
since a compat tag of published wheel was changed from manylinux2010
to manylinux2014. Thereby pip downloads sdist and builds wheel from it,
build fails due to missing libffi package. We don't want to build
Python distributions locally since the goal of these tests is checking
IPA against pypi's distributions.

pip 19.3 is the first version that supports manylinux2014 tag:
https://pip.pypa.io/en/stable/news/#v19-3

pip 20.0+ in turn, changed its behavior and installs IPA wheels from
pypi.org (same version as our built) instead of locals ones.