ipatest: skip test_replica_uninstall_deletes_ruvs
test_replica_uninstall_deletes_ruvs fails with:
```
FAILED test_integration/test_topology.py::TestCASpecificRUVs::test_replica_uninstall_deletes_ruvs - AssertionError: Replica RUVs were not clean during replica uninstallation

...

        tasks.uninstall_master(replica)
        # ipa-replica-manage del launches a clean-ruv task which is
        # ASYNCHRONOUS
        # wait for the task to finish before checking list-ruv
        tasks.wait_for_cleanallruv_tasks(self.master.ldap_connect())
        res2 = master.run_command(['ipa-replica-manage', 'list-ruv', '-p',
                                  master.config.dirman_password]).stdout_text
>       assert(replica.hostname not in res2), (
            "Replica RUVs were not clean during replica uninstallation")
E       AssertionError: Replica RUVs were not clean during replica uninstallation
E       assert 'replica2.ipa.test' not in 'Replica Upd...est:389: 8\n'
E
E         'replica2.ipa.test' is contained here:
E           Replica Update Vectors:
E           	master1.ipa.test:389: 4
E           	replica1.ipa.test:389: 3
E           Certificate Server Replica Update Vectors:
E           	master1.ipa.test:389: 6
E           	replica1.ipa.test:389: 5
E           	replica2.ipa.test:389: 8
```

See for details:
https://pagure.io/freeipa/issue/8023