alt: ipatests: adapt test_ipa_healthcheck_fips_enabled
Fixes test_ipa_healthcheck_fips_enabled with ipa-healthcheck 0.18:
```
        elif check[0]["kw"]["fips"] == f"missing {paths.FIPS_MODE_SETUP}":
            assert returncode == 127
        else:
>           assert returncode == 1
E           assert 127 == 1

test_integration/test_ipahealthcheck.py:418: AssertionError
```