packaging: move dns-related configs to server-dns subpackage
Problem:
Clean installation of bind and freeipa-server fails (without server-dns):

$ apt-get install bind freeipa-server
...
freeipa-server-4.12.5-alt2         ######################################################################################### [100%]
bind-9.18.39-alt1                  ######################################################################################### [100%]
error: unpacking of archive failed on file /etc/bind: cpio: rename
error: bind-9.18.39-alt1.x86_64: install failed
E: Some errors occurred while running transaction

Reason:
server subpackage depends on server-common for which on
installation, rpm creates /etc/bind *directory* for ghosted configs.
Actual owner of the path is bind package which creates *symlink*
/etc/bind.

Fix description:
bind-related configuration shall be moved to subpackage that depends
on bind to let bind manage its /etc/bind path.

Fixes: https://bugzilla.altlinux.org/56645