Azure CI: do not run test_ipaserver/test_migratepw
Unfortunately, password migration initializes PyCA several times within
the same process. PyCA uses PyO3 which explicitly disables such behavior
and breaks the execution. As a result, the test fails with the following
error message in the logs:

-------------------------------------
 from cryptography.hazmat.bindings._rust import x509 as rust_x509, referer: https://master1.ipa.test/ipa/migration/migration.py
 ImportError: PyO3 modules compiled for CPython 3.8 or older may only be initialized once per interpreter process, referer: https://master1.ipa.test/ipa/migration/migration.py
-------------------------------------

This was introduced in in 2022 with the following commit:
https://github.com/PyO3/pyo3/commit/f17e70316751285340508d0009103570af7e0873
and means the test always fails to detect the recent Python 3.9+ (Fedora
42 runs on Python 3.13).

Fedora's PyO3 build allows to re-enable unsafe sub-interpreters but it has
to be enabled within the package using pyo3 rust crate, e.g. PyCA. PyCA
is built without this support.

Disable the test until we find out how to fix this mess.

Signed-off-by: Alexander Bokovoy <abokovoy@redhat.com>
Reviewed-By: Florence Blanc-Renaud <flo@redhat.com>
Reviewed-By: Alexander Bokovoy <abokovoy@redhat.com>
Reviewed-By: Rob Crittenden <rcritten@redhat.com>