ipatests: make use of platform specific openssl paths in TestPkinitClientInstall
TestPkinitClientInstall tests were not platform agnostic and
hardcoded openssl paths. This led to tests failure.

Fixes:
```
FAILED test_integration/test_pkinit_install.py::TestPkinitClientInstall::test_client_install_pkinit - subprocess.CalledProcessError: Command '['tee', '/etc/pki/tls/private/clien...

```
=================================== FAILURES ===================================
______________ TestPkinitClientInstall.test_client_install_pkinit ______________

self = <ipatests.test_integration.test_pkinit_install.TestPkinitClientInstall object at 0x7f4566b86a20>

    def test_client_install_pkinit(self):
        tasks.kinit_admin(self.master)
        self.add_certmaperule()
        self.add_host()
>       self.create_cert()

test_integration/test_pkinit_install.py:119:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_integration/test_pkinit_install.py:102: in create_cert
    client.put_file_contents(filename, data)
/usr/lib/python3/site-packages/pytest_multihost/host.py:195: in put_file_contents
    self.transport.put_file_contents(filename, contents, encoding=encoding)
/usr/lib/python3/site-packages/pytest_multihost/transport.py:438: in put_file_contents
    cmd.wait()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pytest_multihost.transport.SSHCommand object at 0x7f4566d00a40>
raiseonerr = True

    def wait(self, raiseonerr=DEFAULT):
        """Wait for the remote process to exit

        Raises an exception if the exit code is not 0, unless ``raiseonerr`` is
        true.

        When ``raiseonerr`` is not specified as argument, the ``raiseonerr``
        attribute is used.
        """
        if raiseonerr is DEFAULT:
            raiseonerr = self.raiseonerr

        if self._done:
            return self.returncode

        self._end_process()

        self._done = True

        if raiseonerr and self.returncode:
            self.log.error('Exit code: %s', self.returncode)
>           raise subprocess.CalledProcessError(self.returncode, self.argv)
E           subprocess.CalledProcessError: Command '['tee', '/etc/pki/tls/private/client.key']' returned non-zero exit status 1.

/usr/lib/python3/site-packages/pytest_multihost/transport.py:215: CalledProcessError

...

RUN ['cat', '/etc/pki/tls/certs/client.pem']
Exit code: 0
RUN ['tee', '/etc/pki/tls/certs/client.pem']
Exit code: 0
RUN ['cat', '/etc/pki/tls/private/client.key']
Exit code: 0
RUN ['tee', '/etc/pki/tls/private/client.key']
tee: /etc/pki/tls/private/client.key: No such file or directory
Exit code: 1
```