ipatests: Open NFS firewall port in test_nfs.py
The TestNFS class starts an NFS server on clients[0] but never opens port 2049 in the firewall.
In non-STIG and FIPS environments this goes unnoticed because the firewall is either masked or uses a permissive default zone.
In STIG mode, the hardened security profile enforces a deny-by-default firewall policy, causing NFS mount attempts
from other clients to fail with "No route to host".

Hence both rpc-gssd and gssproxy service are restarted.

['mount', '-t', 'nfs4', '-o', 'sec=krb5p,vers=4.0', 'client1.testrelm.test:/exports/home', '/home', '-v']
mount.nfs4: mount(2): No route to host

subprocess.CalledProcessError: Command '['systemctl', 'status', 'gssproxy']' returned non-zero exit status 3.

Fixes: https://codeberg.org/freeipa/freeipa/issues/10014

Signed-off-by: Sudhir Menon <sumenon@redhat.com>
Reviewed-By: Jay Gondaliya <jgondali@redhat.com>
Reviewed-By: PRANAV THUBE <pthube@redhat.com>
Reviewed-By: Anuja More <amore@redhat.com>
Reviewed-By: Florence Blanc-Renaud <flo@redhat.com>