alt: ipatests: install required libsss_sudo for test_install_sudo_on_client
libsss_sudo was removed in previous test and apt complains about
unmet dependencies.

FAILED test_integration/test_installation.py::TestInstallWithoutSudo::test_install_sudo_on_client - subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', 'sudo'...

RUN ['apt-get', 'install', '-y', 'sudo']
Reading Package Lists...
Building Dependency Tree...
You might want to run `apt-get --fix-broken install' to correct these:
The following packages have unmet dependencies:
  freeipa-client: Depends: libsss_sudo
E: Unmet dependencies. Try 'apt-get --fix-broken install' with no packages (or specify a solution).
Exit code: 100
The following packages have unmet dependencies:
  freeipa-client: Depends: libsss_sudo
E: Unmet dependencies. Try 'apt-get --fix-broken install' with no packages (or specify a solution).

So install it first.