pylint: Fix unnecessary-dict-index-lookup
Pylint 2.9 introduced new check:
> New checker unnecessary-dict-index-lookup. Emitted when iterating over
dictionary items (key-value pairs) and accessing the value by index
lookup.

Note: in Python3 removing from dict during an iteration is not
possible. For example,
```
cat a.py
d = {"a": 1}

for k, v in d.items():
    if v is not None:
        del d[k]

python3 a.py
Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/freeipa/test.py", line 3, in <module>
    for k, v in d.items():
RuntimeError: dictionary changed size during iteration
```